### ISSUE TITLE
Correct thirdparty URL in Readme.md

### ISSUE THREAD

**Issue by scorpioluck20** [GeniusVentures/SuperGenius#13]
Part:Download thirdparty project In Readme.md file
We should correct thirdparty URL

> git clone git@github.com:GeniusVentures/SuperGenius.git--recursive 

It should be

> git clone git@github.com:GeniusVentures/thirdparty.git --recursive

**Comment by MSaiTeja01** [comment]
I can take a look at it.
Will raise a PR shortly :)

**Comment by dhairya-rathod** [comment]
@MSaiTeja01 I already raised a PR for this.
